Zenoh S3 Backend
DariusIMP/zenoh-backend-s3 pull request #3
Opened 2022-10-10 15:07 UTC by DariusIMP

First PR for the Zenoh S3 backend (see the [discussion](https://github.com/eclipse-zenoh/roadmap/discussions/53) and the [roadmap issue](https://github.com/eclipse-zenoh/roadmap/issues/54).

The code from this PR has been manually tested with a local instance of a MinIO server running on docker. So far we can:
* Create the storage on a S3 instance retrieving the configuration parameters from the json5 configuration file
* Perform:
  * PUT operations
  * GET operations
  * DELETE operations
* We can delete the bucket upon deletion of the storage (if configured)
* Put/retrieve files with MIME type encoding.

For this feature we are using Amazon's crate [aws-sdk-s3](https://crates.io/crates/aws-sdk-s3) which although is on a beta stage will probably be more fit to support this feature in the future.

**How to run the manual tests**

It is explained on the README document of this PR. Basically:

1 - launch a MinIO instance:
```
docker run -p 9000:9000 -p 9090:9090  --user $(id -u):$(id -g)  --name minio1 -e 'MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE' -e 'MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'  -v ${HOME}/minio/data:/data   quay.io/minio/minio server data --console-address ':9090'"
```

2 - Launch zenohd with the json5 config file from this PR
```
zenohd -c zenoh.json5
```

3 - Perform some of the possible operations using `curl`, for instance:

```
# Put values that will be stored in the S3 storage
curl -X PUT -H 'content-type:application/json' -d '{"example_key": "example_value"}' http://0.0.0.0:8000/s3/example/test

# To get the stored object
curl -X GET -H {} -d '{}' http://0.0.0.0:8000/s3/example/test

# To delete the previous object
curl -X DELETE -H {} -d '{}' http://0.0.0.0:8000/s3/example/test

# To delete the whole storage (and the bucket if configured)
curl -X DELETE 'http://0.0.0.0:8000/@/router/local/config/plugins/storage_manager/storages/s3_storage'

# To delete the whole volume
curl -X DELETE 'http://0.0.0.0:8000/@/router/local/config/plugins/storage_manager/volumes/s3'
```

-----

Observation: this PR is the result of modifying the rocksdb plugin codebase to fit this requirement, so that's why the diffbase will be performed over that code.

2022-10-12 07:29 UTC, Mallets requested changes

2022-10-12 14:16 UTC, DariusIMP commented on src/lib.rs
>      };
In this place I'm also checking the type of the retrieved value (which must be a string). It's not so obvious to me how to replace that logic with ok_or_else. How would you implement it?

2022-10-12 14:32 UTC, Mallets commented on src/lib.rs
>      };
I would do it as follows:
```rust
    let endpoint = match config
        .rest
        .get(PROP_S3_ENDPOINT)
        .ok_or_else(|| zerror!("Mandatory property `{}` for S3 Backend not provided", PROP_S3_ENDPOINT))?
    {
        serde_json::Value::String(endpoint) => endpoint.clone(),
        _ => bail!(
            "Mandatory property `{}` for S3 Backend must be a string",
            PROP_S3_ENDPOINT
        ),
    };
```
In this way, two different message errors can be returned:
- the config parameter has not been set
- the config parameter exists but it hasn't got the right encoding

With the actual implementation, the only error message returned to the user is that the parameter is not a String, even if the user forget to pass that parameter.

2022-10-13 07:31 UTC, DariusIMP commented on src/lib.rs
>              }
Yea, my bad. What if the error thrown is that the bucket already exists and you already own it? Shouldn't we just throw a warning?

2022-10-17 09:15 UTC, DariusIMP commented on README.md
> +                reuse_bucket: true,
Related to how to create the storage, I ended up figuring out this was the cleanest way to handle the issue of "what if the bucket already exists, should we throw an error or not?". We always should try to create the bucket, and if it already exists and is owned by the user, and this flag is set as true, then we should proceed with that existing bucket, I think, otherwise return error.
Shouldn't we first verify if the bucket already exists and is owned by the user before attempting to create the bucket? The answer is that with the amazon api as it is it's best to directly attempt to create the bucket, if it was not the case then the bucket is created and if it was the case then it returns an error we can handle.

2022-10-17 09:17 UTC, DariusIMP commented on zenoh.json5
> +            reuse_bucket: true,
Related to how to create the storage, I ended up figuring out this was the cleanest way to handle the issue of "what if the bucket already exists, should we throw an error or not?". We always should try to create the bucket, and if it already exists and is owned by the user, and this flag is set as true, then we should proceed with that existing bucket, I think, otherwise return error.
Shouldn't we first verify if the bucket already exists and is owned by the user before attempting to create the bucket? The answer is that with the amazon api as it is it's best to directly attempt to create the bucket, if it was not the case then the bucket is created and if it was the case then it returns an error we can handle.

2022-10-17 09:24 UTC, DariusIMP commented on src/lib.rs
>              }
Added a comment on the zenoh.json5 file on how I modified this. We can keep the discussion over there.

2022-10-20 13:20 UTC, DariusIMP commented
Update: I have been testing this code with AWS S3 and ended up doing some modifications to the config file in order to ease the usage by the user and make compatible this plugin with both MinIO and AWS S3 storages. For that I moved the region field to be a volume configuration rather than a storage configuration. Why? Because with AWS, the url and the region must be consistent, you can't put an url being `"https://s3.eu-west-1.amazonaws.com"` and the region being `us-east-1` because they differ and aws complains. So with the previous config, all the storages associated to a volume should all have a same region that in turn must be consistent with the url from the volume. Making the region be a volume config is a solution to that, this makes all the storages be on the same region as specified without place to mistakes. On top of that, from the region the aws endpoint resolver automatically retrieves the proper endpoint, so the url is no more a mandatory field, as with only the region we get the endpoint.

However when using MinIO, it's different. The region is not required by MinIO, but it is necessary to specify the endpoint. So the region is turned now as an optional value for these cases.

2022-12-06 15:52 UTC, DariusIMP commented
Closing this PR, as this codebase with further changes was integrated into the eclipse repository: https://github.com/eclipse-zenoh/zenoh-backend-s3.

2022-12-06 15:52 UTC, closed without merging